version: '3.8'

services:
  ai-travel-planner:
    build: .
    container_name: ai-travel-planner
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # 持久化数据
    environment:
      # 基础配置
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./data/travel_planner.db}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=${DEBUG:-False}
      
      # 阿里云百炼 API（AI 功能）
      - ALIYUN_BAILIAN_API_KEY=${ALIYUN_BAILIAN_API_KEY}
      - ALIYUN_BAILIAN_APP_ID=${ALIYUN_BAILIAN_APP_ID}
      
      # 阿里云语音识别 API（语音功能）
      - ALIYUN_ASR_APP_KEY=${ALIYUN_ASR_APP_KEY}
      - ALIYUN_ASR_ACCESS_KEY_ID=${ALIYUN_ASR_ACCESS_KEY_ID}
      - ALIYUN_ASR_ACCESS_KEY_SECRET=${ALIYUN_ASR_ACCESS_KEY_SECRET}
      
      # 高德地图 API（地图功能）
      - AMAP_API_KEY=${AMAP_API_KEY}
      - AMAP_WEB_SERVICE_KEY=${AMAP_WEB_SERVICE_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ai-travel-network

networks:
  ai-travel-network:
    driver: bridge

volumes:
  data:
    driver: local